.TH INCLUDE 1 August\ 2019 local

.SH NAME
include \- file inclusion

.SH SYNOPSIS
\fBinclude\fP [-m N] [\fIfile\fP]

.SH DESCRIPTION
\fBinclude\fP copies \fIfile\fP to standard output unchanged,
except that each line beginning
.PP
.nf
.RS
#include "\fIfilename\fP"
.RE
.fi
.PP
is replaced by the contents of the file whose name is \fIfilename\fP.
If \fIfile\fP is not specified, standard input is read instead.
If \fIfilename\fP is not an absolute path, it is taken relative to the
current file's directory (the current working directory if reading stdin).
Include files may contain further \fB#include\fP lines, up to the depth
specified by \fB-m\fP \fIN\fP (default is 5).

.SH EXAMPLE
.nf
#include "globals.h"
int main() {
  return THEANSWER;
}
.fi
