.TH ECHO 1 July\ 2019 local
.SH NAME
echo \- copy arguments to standard output
.SH SYNOPSIS
\fBecho\fP [\fIargument\fP ...]
.SH DESCRIPTION
\fBecho\fP copies its command line arguments to its standard output
as a line of text with one space between each argument.
If there are no arguments, an empty line is produced (just a newline).
.SH EXAMPLE
To see if your system is alive:
.PP
.nf
.RS
$ \fBecho\fP hello world!
\fIhello world!\fP
.RE
.fi
